spring:
  http:
    encoding:
      enabled: true
      charset: UTF-8
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB
  jackson:
    time-zone: America/Sao_Paulo
    serialization.INDENT_OUTPUT: true
  datasource:
    url: jdbc:h2:mem:bestroutedb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
info:
  app:
    name: '@name@'
    description: '@project.description@'
  build:
    groupId: '@project.groupId@'
    artifactId: '@project.artifactId@'
    name: '@project.name@'
    version: '@project.version@'